datadog:
  apiKeyExistingSecret: datadog-secret
  site: "datadoghq.com"
  clusterName: "stroke-cluster"
  logs:
    enabled: true
  apm:
    enabled: true
  processAgent:
    enabled: true
  networkMonitoring:
    enabled: true

clusterAgent:
  enabled: true
  replicas: 2
  createPodDisruptionBudget: true
  admissionController:
    enabled: true
